### ISSUE TITLE
Possible errors in videos 

### ISSUE THREAD

**Issue by Kimed** [SeanPesce/DXMD-Translations#6]
These two video sequences might have been parsed wrong (unless data itself is invalid, of course):

[[assembly:/scenes/game/20_prague/pra_master.entity].pc_resourcelibdef](0009).pc_resourcelib video_id=7901045612977460 invalid end time ""
[[assembly:/scenes/dlc_01/20_breach/breach_global.entity].pc_resourcelibdef](0010).pc_resourcelib video_id=52920086065632881 invalid end time "32.5.37"

**Comment by SeanPesce** [comment]
I believe a missing end-time just tells the game to continue displaying that subtitle until the end of the video, but I could be wrong.

As for the one with "32.5.37", I remember seeing that but I forgot to fix it. From what I can tell, that's the real value from the game files. We should probably just watch the cutscene and give it an appropriate timestamp.

Are you making a GUI for editing the JSON files? If so, an important aspect of the cutscene subtitles (e.g., the ones with start/end timestamps) is that we can easily add/remove new entries and/or modify their start/end times. That would be a nice feature to include in a GUI editor IMO.

**Comment by Kimed** [comment]
>I believe a missing end-time just tells the game to continue displaying that subtitle until the end of the video,

Well, finding that dialogue in game would require to dig a lot of saves to find one for replaying, but I doubt it'd be the case
<html>
<body>

4.23 :   8.50 | Alex, I'm in. Anything I need to know before I start up this chair?
-- | --
**7.656** : | .
9.13 :  17.73 | Every NSN is different, man, so I'm not sure what to expect. I’m guessing you'll end up in some kind of virtual conference room. No one else should be in there
18.93 :  20.00 | And if they are?
20.43 :  23.40 | They'll see you as Miller. So say something snippy and log off.
24.80 :  28.33 | Huh, okay... Where do I find these stored conversations?
28.97 :  36.80 | Hell if I know. This is your plan. But holographic recordings take up a lot of virtual memory, so you may have to look in several places.
38.53 :  41.53 | I’ll just have to play it by ear.
41.90 :  53.13 | Exactly. The whisper-chip is still in place, though, so we'll both know when you've done it. Good luck, Adam.
</body>
</html>

If the start time is to be trusted, a single dot must appear somewhere while the first line is played. It looks like it *might* be a fault in original data (context-wise I don't see anything missing in the dialogue), but can't say for sure without peeking inside data files.

The second one looks like it *is* missing a piece, though
<html>
<body>

0.90 :   6.73 | Back now to that confusing tale of life... or is it death? ... coming out of the United States.
-- | --
7.30 :  13.40 | Sources tell me that a yet-to-be-identified group of mercenaries broke into a cutting-edge VersaLife research facility,
14.33 :  19.09 | hoping to find and rescue this girl: Lindsey Thompson.
19.10 :  23.53 | The group claims VersaLife has been using the six-year-old as a test subject
29.10 : 32.5.37 | VersaLife emphatically denies the salacious claim,
79.30 :  84.57 | This is Eliza Cassan, reporting to you live -- from Picus.

</body>
</html>

Between 32.5 and 79.30, I believe there has to be a lot of text (unless the whole particular newsflash is scrapped by devs, that is).

>Are you making a GUI for editing the JSON files?

That's the plan, yes.

>If so, an important aspect of the cutscene subtitles (e.g., the ones with start/end timestamps) is that we can easily add/remove new entries and/or modify their start/end times. That would be a nice feature to include in a GUI editor IMO.

Not sure how could it be used (unless somebody is doing a mod, which I don't see happening). Also not sure how the engine would react to changed amount of lines in JSON's entry. But if there's a significant amount of timing bugs in original cutscenes (don't remember it happening either in my playthrough, but whatever), that can be a way to fix it, probably.

**Comment by SeanPesce** [comment]
Good call, that data doesn't seem correct. I'll look at the original game files again to see how it compares.

> Not sure how could it be used

I've already done it several times, because some things don't have subtitles in the original cutscenes (e.g., the guy yelling in Arabic in the game intro). Like you said, it's also useful for fixing some of the more awkwardly-timed cutscene subtitles.

> Also not sure how the engine would react to changed amount of lines in JSON's entry.

Don't worry about that -- the JSON parser is part of my code; the game isn't even aware of it.  Injection of new cutscene subtitles works fine, but injection of new in-game subtitles (e.g., for NPC dialog) isn't possible (yet?).

**Comment by SeanPesce** [comment]
Fixed while working on #1 (thanks @Kimed!)
