### ISSUE TITLE
Deus Ex: Mankind Divided won't start ("Unrecognized game version: ae3d1f9239eb9630d99b83bbc8a28ad2")

### ISSUE THREAD

**Issue by OnizukaHUN** [SeanPesce/DXMD-Translations#8]
[DXMD_Mod.log](https://github.com/SeanPesce/DXMD-Translations/files/15141488/DXMD_Mod.log)
I get this message.
![DXMD Mod Debug 2024-04-28](https://github.com/SeanPesce/DXMD-Translations/assets/168335400/1d48d44c-44ab-4c7a-bb8f-bbe47bee6b19)
If I delete the versio.dll file, it starts, but not in the desired language. But in the original, English.
Can you help me, what could be wrong?
The game is original.
About Epic Games.

**Comment by SeanPesce** [comment]
I have added support for the Epic Games Store version; see [here](https://github.com/SeanPesce/DXMD-Translations/releases).
